export const theme = {
  colors: {
    white: '#fff',
    black: '#000',
    red: '#EB5757',
    green: '#27AE60',
    orange: '#FCDBC1',
    accentPrimary: '#216CFF',
    accentSecondary: '#F447AF',
    grayPrimary: '#0F0F11',
    graySecondary: '#89939A',
    grayIcons: '#B4BDC3',
    grayElements: '#E2E6E9',
    grayBackground: '#FAFBFC',
  },
  fonts: {
    name: 'Montserrat, sans-serif',
    sizeXxs: '12px',
    sizeXs: '14px',
    sizeS: '16px',
    sizeM: '20px',
    sizeL: '22px',
    sizeXxl: '32px',
    sizeXxxl: '48px',
    weightRegular: 'regular',
    weightSemiBold: 'semibold',
    weightBold: 'bold',
    lineHeightXxs: '11px',
    lineHeightXs: '11px',
    lineHeightS: '15px',
    lineHeightM: '21px',
    lineHeightL: '26px',
    lineHeightXl: '31px',
    lineHeightXxl: '41px',
    lineHeightXxxl: '56px',
    spacingS: '-0.01em',
    spacingDefault: '0',
    spacingM: '0.04em',
  },
  transition: {
    slower: '0.2s cubic-bezier(0.4, 0, 0.2, 1)',
    faster: '0.5s cubic-bezier(0.4, 0, 0.2, 1)',
  },
};
